# Generated by Django 4.2.7 on 2023-12-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_manage', '0004_alter_purchase_acknowledgment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='delivery_date',
            new_name='expected_delivery_date',
        ),
        migrations.AddField(
            model_name='purchase',
            name='actual_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
