# Generated by Django 4.2.7 on 2023-12-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_manage', '0005_rename_delivery_date_purchase_expected_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='issue_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
