# Generated by Django 4.2.7 on 2023-12-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_manage', '0006_alter_purchase_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
