# Generated by Django 4.2.7 on 2023-12-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_manage', '0008_alter_purchase_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperformance',
            name='date',
            field=models.DateTimeField(unique=True),
        ),
    ]
