# Generated by Django 4.2.7 on 2023-12-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_manage', '0013_alter_purchase_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='items',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
