# Generated by Django 4.2.7 on 2023-12-12 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_manage', '0015_alter_vendor_quality_rating_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order', to='vendor_manage.vendor'),
        ),
    ]
