# Generated by Django 4.2.7 on 2023-12-13 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_manage', '0016_alter_purchase_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='expected_delivery_date',
            new_name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='actual_delivery_date',
        ),
        migrations.AlterField(
            model_name='historicalperformance',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='vendor_manage.vendor'),
        ),
    ]
