# Generated by Django 4.2.7 on 2023-12-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_manage', '0019_alter_purchase_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='order_date',
            field=models.DateTimeField(),
        ),
    ]
